[project]
name = "mle-01-p2-team1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "langchain>=1.4.0",
    "langchain-core>=1.6.2",
    "langchain-openai>=1.6.2",
    "neo4j>=6.3.0",
    "openai>=3.11.0",
    "pandas>=3.0.5",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "pytest>=9.1.1",
]
